config/routes.rb
Rails.application.routes.draw do



  root 'static_pages#home'

  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :user_groups
  resources :novels
  resources :categories
  resources :chapters, only: [:create, :destroy, :show, :update, :edit, :new]
  resources :novel_comments, only: [:create, :destroy, :update]
  resources :chapter_comments, only: [:create, :destroy, :update]
  resources :chapter_votes, only: [:create, :destroy, :update]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user_group
  has_many :chapters, class_name: 'Chapter', foreign_key: :author_id
  has_many :chapter_comments
  has_many :chapter_votes
  has_many :novel_comments
  has_many :roles

  validates_associated :user_group
  validates :user_group_id, presence: true
  validates :user_name, uniqueness: true, presence: true,
            format:{with: /\A[a-zA-Z0-9_@$.]+\z/i, message: I18n.t('my.errors.signup.validations.user_name')}
  validates :nick_name, presence: true
  validates :user_group_id, presence: true
  validates :level, presence: true, numericality: {greater_than: 0}
  validates :password_digest, presence: true

  attr_accessor :remember_token #, :activation_token, :reset_token

  # 密码
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  ######### 类方法 ############

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
        BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # 返回随机令牌
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  ############ 实例方法 ###########

  def vote_chapter(chapter_id, positive)
    am=chapter_votes.where(chapter_id: chapter_id)
    if am.any?
       if am.first.rate == (positive ? level : -level)
         return false
       else
         am.first.destroy
         ChapterVote.create(
             chapter_id: chapter_id,
             user_id: id,
             rate: (positive ? level: -level)
         )
       end
    else
      ChapterVote.create(
          chapter_id: chapter_id,
          user_id: id,
          rate: (positive ? level: -level)
      )
    end
  end

  def permissions
    self.user_group.user_group_own_permissions
        .where('user_level <= ?', self.level)
  end

  # 检查用户是否拥有某权限
  def has_permission?(permission_id)
    self.user_group.user_group_own_permissions
        .where('user_level <= ? and permission_id = ?', self.level, permission_id).any?
  end

  # 在数据库中记住我
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 忘记我
  def forget
    update_attribute(:remember_digest, nil)
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end


  private


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action 'has_permission?(Permission::MANAGE_USERS)',   only: [:destroy]
  before_action 'has_permission?(Permission::VIEW_USERS)',   only: [:index]


  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user=User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    convert_header_data
    @user=User.new(user_params)
    @user.level=1
    @user.user_group_id=UserGroup.common_user_group.id

    if @user.save
      log_in @user
      flash[:info] = I18n.t('my.notice.sign_up_success')
      redirect_to root_url
    else
      render 'new'
    end
  end


  def update
    convert_header_data
    old_password=params[:user][:old_password]
    if old_password.blank? or not @user.authenticate(old_password)
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end
    if @user.update_attributes(user_params)
      flash[:success] = t('my.notice.update_success')
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = I18n.t('my.notice.remove_success')
    redirect_to users_url
  end

  def edit
  end

  private

    def user_params
      params.require(:user).permit(:user_name, :nick_name,
                                   :password, :password_confirmation,
                                    :header)
    end

    def convert_header_data
      header_data=get_pic_str(params[:user][:header])
      params[:user][:header]=header_data
    end
    # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper

  def header_tag(user)
    if user and user.header
      "<img class='header' src='#{user.header}' alt='#{user.user_name}' />".html_safe
    else
      image_tag 'default_header.jpg', class: 'header', alt: user.user_name if user
    end
  end
end

app/views/users/_user.html.haml
%li
  = link_to header_tag(user), user
  = link_to user.user_name, user
  - key_name = "activerecord.attributes.user_group.#{user.user_group.name}"
  (#{ t(key_name) } #{ user.level } 级)

  - if current_user.has_permission?(Permission::MANAGE_USERS)
    = link_to t('pages.delete'), user, method: :delete,  data: { confirm: t('pages.confirm') }

app/views/users/edit.html.haml
- provide :title, t('page_title.edit_profile')
%h1
  = t('page_title.edit_profile')

.row
  .col-md-6.col-md-offset-3
    = form_for(@user, html: { multipart: true }) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :user_name, t('activerecord.attributes.user.user_name')
      = f.text_field :user_name, class: 'form-control', disabled:true

      = f.label :nick_name, t('activerecord.attributes.user.nick_name')
      = f.text_field :nick_name, class: 'form-control'

      = f.label :header, t('activerecord.attributes.user.header')
      = f.file_field :header, class: 'form-control'

      = f.label :old_password, t('activerecord.attributes.user.old_password')

      = f.password_field :old_password, class: 'form-control'

      = f.label :password, t('activerecord.attributes.user.password')
      = f.password_field :password, class: 'form-control'

      = f.label :password_confirmation, t('activerecord.attributes.user.password_confirmation')
      = f.password_field :password_confirmation, class: 'form-control'

      = f.submit t('pages.edit'), class: 'btn btn-primary'



:javascript
  // 下面的代码用于限制上传文件的大小
  $('#user_header').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024;
    if (size_in_megabytes > 50) {
      alert(#{t('my.errors.login.validations.header_picture_too_big')});
    }
  });

app/views/users/index.html.haml
- provide :title, t('pages.user_manage')

%h1
  = t('pages.user_manage')

= will_paginate @users

%ul.users
  = render @users

= will_paginate

app/views/users/new.html.haml
- provide :title, t('page_title.signup')
%h1
  = t('pages.signup')

.row
  .col-md-6.col-md-offset-3
    = form_for(@user, html: { multipart: true }) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :user_name, t('activerecord.attributes.user.user_name')
      = f.text_field :user_name, class: 'form-control'

      = f.label :password, t('activerecord.attributes.user.password')
      = f.password_field :password, class: 'form-control'

      = f.label :password_confirmation, t('activerecord.attributes.user.password_confirmation')
      = f.password_field :password_confirmation, class: 'form-control'

      = f.label :nick_name, t('activerecord.attributes.user.nick_name')
      = f.text_field :nick_name, class: 'form-control'

      = f.label :header, t('activerecord.attributes.user.header')
      = f.file_field :header, class: 'form-control'

      = f.submit t('pages.signup'), class: 'btn btn-primary'

:javascript
  // 下面的代码用于限制上传文件的大小
  $('#user_header').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024;
    if (size_in_megabytes > 50) {
      alert(#{t('my.errors.login.validations.header_picture_too_big')});
    }
  });

app/views/users/show.html.haml
- provide :title, @user.nick_name

.row
  %aside.col-md-4
    %section.user_info
      %h1
        = header_tag(@user)
        = @user.nick_name
      %section.stats
        写了 #{@user.chapters.count}  章小说

  .col-md-8
    下面是你写的小说

    %table.table
      %thead
        %tr
          %th
            章节
          %th
            书名
          %th
            最后更新时间

      - @user.chapters.order(:updated_at).each do |chapter|
        %tbody
          %tr
            %td
              = link_to "第 #{chapter.number} 章 #{chapter.title}", chapter_path(chapter)
            %td
              = link_to "<< #{chapter.novel.name} >>", novel_path(chapter.novel)
            %td
              #{chapter.updated_at}