config/routes.rb
Rails.application.routes.draw do



  root 'static_pages#home'

  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :user_groups
  resources :novels
  resources :categories
  resources :chapters, only: [:create, :destroy, :show, :update, :edit, :new]
  resources :novel_comments, only: [:create, :destroy, :update]
  resources :chapter_comments, only: [:create, :destroy, :update]
  resources :chapter_votes, only: [:create, :destroy, :update]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/novel.rb
class Novel < ActiveRecord::Base
  belongs_to :category
  has_many :chapters
  has_many :novel_comments
  has_many :roles

  validates :name, presence: true
  validates :category_id, presence: true
  validates_associated :category

  class Status
    WORKING=0
    FINISHED=1


    def self.names
      @names||=%w(连载中 已完结)
    end

  end

  def working?
    status == Status.WORKING
  end
  def finished?
    status == Status.FINISHED
  end

  def self.working_novels
    Novel.all.where(status: Status::WORKING)
  end
  def self.finished_novels
    Novel.all.where(status: Status::FINISHED)
  end

  # 获取所有定版章节
  def all_finished_chapters
    self.chapters.where(status: Chapter::Status::LOCK).order(:number)
  end


  # 获取所有活跃章节
  def all_active_chapters
    self.chapters.where(status: Chapter::Status::ACTIVE).order(:number)
  end

  # 获取活跃章节号
  def active_chapter_num
    last=all_finished_chapters.last
    last.nil?? 1 : (last.number + 1)
  end

  # 获取所有概要
  def all_summary
    all_finished_chapters.reorder('number desc').select(:number, :title, :summary)
  end

  # 获取所有伏笔
  def all_foreshadowing
    all_finished_chapters.reorder('number desc').select(:number, :title, :foreshadowing)
  end

  def new_chapter_num(user)
    last=all_finished_chapters.last
    my_active_chapter_num=chapters.where(author_id: user.id).order(:number).last
    if my_active_chapter_num.nil?
      last.nil?? 1 : (last.number + 1)
    elsif last.nil?
      my_active_chapter_num.number + 1
    elsif last.number > my_active_chapter_num.number
      last.number + 1
    else
      my_active_chapter_num.number + 1
    end
  end
end

app/controllers/novels_controller.rb
class NovelsController < ApplicationController

  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]
  before_action 'has_permission?(Permission::MANAGE_NOVELS)', only: [:edit, :create, :update, :destroy]

  def index
    @novels=Novel.all
  end

  def new
    @novel=Novel.new
  end

  def show
    @novel=Novel.find(params[:id])
  end

  def create
    convert_cover_data
    @novel = Novel.new
    if @novel.update_attributes(novel_params)
      flash[:success] = t('my.notice.add_success')
      redirect_to @novel
    else
      render 'new'
    end

  end

  def destroy
    Novel.find(params[:id]).destroy
    flash[:success] = I18n.t('my.notice.remove_success')
    redirect_to novels_path
  end

  def update
    convert_cover_data
    @novel = Novel.find(params[:id])
    if @novel.update_attributes(novel_params)
      flash[:success] = t('my.notice.update_success')
      redirect_to @novel
    else
      render 'edit'
    end
  end

  def edit
    @novel=Novel.find(params[:id])
  end

  def novel_params
    params.require(:novel).permit(:name, :cover, :category_id, :status, :description)
  end


  def convert_cover_data
    header_data=get_pic_str(params[:novel][:cover])
    params[:novel][:cover]=header_data
  end
end

app/helpers/novels_helper.rb
module NovelsHelper

  def cover_tag(novel)
    if novel and novel.cover
      "<img class='cover' src='#{novel.cover}' alt='#{novel.name}' />".html_safe
    else
      image_tag 'default_cover.jpg', class: 'cover', alt: novel.name
    end
  end

  def little_cover_tag(novel)
    if novel and novel.cover
      "<img class='little_cover' src='#{novel.cover}' alt='#{novel.name}' />".html_safe
    else
      image_tag 'default_cover.jpg', class: 'little_cover', alt: novel.name
    end
  end


  def status_for_select_tag
    [
      [Novel::Status.names[0], Novel::Status::WORKING],
      [Novel::Status.names[1], Novel::Status::FINISHED],
    ]
  end
end

app/views/novels/_comments.html.haml
- user=novel_comment.user
- if user
  %table.novel_comment.table.table-striped
    %tr.row
      %td.col-md-4
        = header_tag(novel_comment.user)
        = novel_comment.user.nick_name
      %td.col-md-8.text-right
        = novel_comment.created_at
    %tr.row
      = to_html novel_comment.content

app/views/novels/_little_cover_novel.html.haml
%li.novel.col-md-3
  .row
    = link_to little_cover_tag(novel), novel, class: 'col-md-3'
    .col-md-9
      %p
        = link_to novel.name, novel
      %p
        = link_to t('pages.edit'), edit_novel_path(novel)
        = link_to t('pages.delete'), novel, method: :delete, data: { confirm: t('pages.confirm') }

app/views/novels/_novels.html.haml
.row
  %h4.col-md-8 连载小说
  .col-md-4.text-right
    排序:
    = link_to '人气', '#'
    = link_to '名字', '#'
    = link_to '类型', '#'


.novels.row
  - @novels.where(status: Novel::Status::WORKING).each do |novel|
    = render 'little_cover_novel', novel: novel

.row
  %h4.col-md-8  完结小说
  .col-md-4.text-right
    排序:
    = link_to '人气', '#'
    = link_to '名字', '#'
    = link_to '类型', '#'


.novels.row
  - @novels.where(status: Novel::Status::FINISHED).each do |novel|
    = render 'little_cover_novel', novel: novel

app/views/novels/edit.html.haml
- title="#{t('pages.edit')}小说: #{@novel.name}"
- provide :title, title

%h1
  = title

.row
  .col-md-6.col-md-offset-3
    = form_for(@novel) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :name, t('activerecord.attributes.novel.name')
      = f.text_field :name, class: 'form-control'

      = f.label :cover, t('activerecord.attributes.novel.cover')
      = f.file_field :cover, class: 'form-control'

      = f.label :description, t('activerecord.attributes.novel.description')
      = f.text_area :description, class: 'form-control'


      = f.label :category_id, t('activerecord.attributes.novel.category_id')
      = f.collection_select :category_id, Category.all, :id, :name, prompt: true

      = f.label :status, t('activerecord.attributes.novel.status')
      = f.select :status, status_for_select_tag

      = f.submit t('pages.edit'), class: 'btn btn-primary'

app/views/novels/index.html.haml
- provide :title, t('pages.header.novel_manage')

.row
  %h3.col-md-8
    = t('pages.header.novel_manage')
  .col-md-4.text-right
    = link_to t('pages.add'), new_novel_path, class: 'btn btn-default'

= render 'novels' , novels: @novels

app/views/novels/new.html.haml
- title=t('pages.add')
- provide :title, title

%h1
  = title

.row
  .col-md-6.col-md-offset-3
    = form_for(@novel) do |f|
      = render 'shared/error_messages', object: f.object
      = f.label :name, t('activerecord.attributes.novel.name')
      = f.text_field :name, class: 'form-control'

      = f.label :cover, t('activerecord.attributes.novel.cover')
      = f.file_field :cover, class: 'form-control'

      = f.label :description, t('activerecord.attributes.novel.description')
      = f.text_area :description, class: 'form-control'


      = f.label :category_id, t('activerecord.attributes.novel.category_id')
      = f.collection_select :category_id, Category.all, :id, :name, prompt: true

      = f.label :status, t('activerecord.attributes.novel.status')
      = f.select :status, status_for_select_tag

      = f.submit t('pages.add'), class: 'btn btn-primary'

app/views/novels/show.html.haml
- provide :title, @novel.name

.row
  %h3.col-md-8
    = @novel.name
  .col-md-4.text-right
    - if logged_in?
      = link_to '添加新章节', new_chapter_path(novel:@novel.id), class: 'btn btn-default'

.row
  %aside.col-md-4
    %section.novel_info
      = cover_tag(@novel)
      - if logged_in? and current_user.has_permission?(Permission::MANAGE_NOVELS)
        %p= link_to t('pages.edit'), edit_novel_path
      %p 名字: #{@novel.name}
      %p
        类型:
        = link_to @novel.category.name , @novel.category
      %p
        状态:
        = link_to Novel::Status.names[@novel.status], '#'
      %p
        内容简介
        = @novel.description
  .col-md-8
    .finish_chapters
      - @novel.all_finished_chapters.each do |chapter|
        %li.row
          .col-md-8= link_to chapter.full_title, chapter
          - unless chapter.author.nil?
            .col-md-4.text-right= link_to  chapter.author.nick_name, chapter.author

    %h4
      活跃章节
    .active_chapters
      - @novel.all_active_chapters.each do |chapter|
        %li.row
          .col-md-8= link_to chapter.full_title, chapter
          .col-md-1.text-left= chapter.chapter_votes.sum(:rate)
          - unless chapter.author.nil?
            .col-md-3.text-right= link_to  chapter.author.nick_name, chapter.author

    %h4
      评论区

    .novel_comments
      - @novel.novel_comments.each do |novel_comment|
        = render 'comments', novel_comment: novel_comment

    - if logged_in?
      %h4
        写评论
      .write_novel_comments
        = form_for(:novel_comment, url: novel_comments_path) do |f|
          /= render 'shared/error_messages', object: f.object
          = hidden_field_tag :novel_id, @novel.id
          = f.text_area :content , class: 'form-control'
          = f.button '提交', class: 'btn btn-default'