config/routes.rb
Rails.application.routes.draw do



  root 'static_pages#home'

  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :user_groups
  resources :novels
  resources :categories
  resources :chapters, only: [:create, :destroy, :show, :update, :edit, :new]
  resources :novel_comments, only: [:create, :destroy, :update]
  resources :chapter_comments, only: [:create, :destroy, :update]
  resources :chapter_votes, only: [:create, :destroy, :update]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  belongs_to :novel
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  belongs_to :cite, class_name: 'Chapter'
  has_many :followings, class_name: 'Chapter', foreign_key: :cite_id

  has_many :chapter_comments
  has_many :chapter_votes

  validates_associated :novel
  validates_associated :author
# validates_associated :cite

  validates :author_id, presence: true
  validates :novel_id, presence: true
  validates :number, presence: true
  validates :status, presence: true
  validates :title, presence: true
  validates :content, presence: true

  default_scope { order(:number) }

  class Status
    ACTIVE=1
    LOCK=2
    TRASH=3

    def self.names
      @names||=%w(活跃章节 定稿章节 废弃章节)
    end
  end

  def full_title
    "第 #{number} 章 #{title}"
  end


end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  before_action :logged_in_user, only: [:create, :edit, :update, :destroy]

  def new
    unless params[:cite_id].blank?
      @chapter=Chapter.find(params[:cite_id]).dup
      @chapter.author_id=nil
      @chapter.cite_id=params[:cite_id]
      @chapter.id=nil
      params[:novel]=@chapter.novel_id
    else
      @chapter=Chapter.new
    end
    @novel=Novel.find(params[:novel])
    @chapter.novel_id=@novel.id
    @chapter.number=@novel.new_chapter_num(current_user)
    has_manage_novel_permission
  end

  def show
    @chapter=Chapter.find(params[:id])
  end

  def create
    cite_id=params[:cite_id]
    @novel=Novel.find(params[:novel_id])
    @chapter=Chapter.new
    user= ( has_manage_novel_permission and !params[:author_name].blank?) ? User.find_by_user_name([:author_name]) : current_user
    params[:chapter][:number]=@novel.new_chapter_num(user)
    params[:chapter][:author_id]=user.id
    params[:chapter][:novel_id]=@novel.id
    params[:chapter][:cite_id]=cite_id
    unless has_manage_novel_permission
      params[:chapter][:status]=Chapter::Status::ACTIVE
    end
    if @chapter.update_attributes(chapter_params)
      flash[:success] = t('my.notice.add_success')
      redirect_to @novel
    else
      render 'new'
    end

  end

  def destroy
    chapter=Chapter.find(params[:id])
    if has_manage_novel_permission or chapter.author.id = current_user.id
      novel=Novel.find(chapter.novel_id)
      if chapter.destroy
        flash[:notice]='删除成功'
        redirect_to novel
      else
        render 'show'
      end
    end
  end

  def update
    @chapter = Chapter.find(params[:id])
    user= ( has_manage_novel_permission and !params[:author_name].blank?) ? User.find_by_user_name([:author_name]) : current_user
    params[:chapter][:author_id]=user.id
    if @chapter.update_attributes(chapter_params)
      flash[:success] = t('my.notice.update_success')
      redirect_to @chapter.novel
    else
      render 'edit'
    end
  end

  def edit
    @chapter=Chapter.find(params[:id])
    has_manage_novel_permission
  end

  def has_manage_novel_permission
    @has_manage_novel_permission||=current_user.has_permission?(Permission::MANAGE_NOVELS)
  end

  def chapter_params
    params.require(:chapter).permit(:novel_id, :number, :author_id,
                                    :status, :cite_id, :title, :content,
                                    :summary, :subsequent_summary, :foreshadowing)
  end

end

app/helpers/chapters_helper.rb
module ChaptersHelper

  def chapter_status_for_select_tag
    [
        [Chapter::Status.names[0], Chapter::Status::ACTIVE],
        [Chapter::Status.names[1], Chapter::Status::LOCK],
        [Chapter::Status.names[2], Chapter::Status::TRASH],
    ]
  end

  def full_number(chapter)
    "第 #{chapter.number} 章 #{chapter.title}"
  end
end

app/views/chapters/_comments.html.haml
- user=chapter_comment.user
- if user
  %table.chapter_comment.table.table-striped
    %tr.row
      %td.col-md-4
        = header_tag(chapter_comment.user)
        = chapter_comment.user.nick_name
      %td.col-md-8.text-right
        = chapter_comment.created_at
    %tr.row
      = to_html chapter_comment.content

app/views/chapters/_foreshadowing.html.haml
%h4
  还没埋的坑

- novel.all_foreshadowing.each do |foreshadowing|
  %p
    %b
      = full_number(foreshadowing)
  %p
    = foreshadowing.foreshadowing

app/views/chapters/_summary.html.haml
%h4
  前情提要
- novel.all_summary.each do |summary|
  %p
    %b
      = full_number(summary)
  %p
    = summary.summary

app/views/chapters/edit.html.haml
- title="修改: 第 #{@chapter.number} 章 #{@chapter.title}"
- provide :title, title

%h3.text-center
  = title

%h4.text-center
  第 #{@chapter.number} 章

.row
  .col-md-3
    = render 'summary', novel: @chapter.novel
    = render 'foreshadowing', novel: @chapter.novel

  .col-md-6
    = form_for(@chapter) do |f|
      = render 'shared/error_messages', object: f.object

      - if @has_manage_novel_permission
        = f.label :number, t('activerecord.attributes.chapter.number')
        = f.text_field :number, class: 'form-control'

        = label :author_name, t('activerecord.attributes.chapter.author_id')
        = text_field_tag :author_name, '',class: 'form-control'

        = f.label :status, t('activerecord.attributes.chapter.status')
        = f.select :status, chapter_status_for_select_tag, class: 'form-control'

      = f.label :title, t('activerecord.attributes.chapter.title')
      = f.text_field :title, class: 'form-control'


      = f.label :content, t('activerecord.attributes.chapter.content')
      = f.text_area :content, class: 'form-control'

      = f.label :summary, t('activerecord.attributes.chapter.summary')
      = f.text_area :summary, class: 'form-control'

      = f.label :subsequent_summary, t('activerecord.attributes.chapter.subsequent_summary')
      = f.text_area :subsequent_summary, class: 'form-control'

      = f.label :foreshadowing, t('activerecord.attributes.chapter.foreshadowing')
      = f.text_area :foreshadowing, class: 'form-control'

      = f.submit t('pages.edit'), class: 'btn btn-primary'

app/views/chapters/new.html.haml
- title="为 #{@novel.name} 添加新章节"
- provide :title, title

%h3.text-center
  = title

%h4.text-center
  第 #{@chapter.number} 章

.row
  .col-md-3
    = render 'summary', novel: @novel
    = render 'foreshadowing', novel: @novel


  .col-md-6
    = form_for(@chapter) do |f|
      = render 'shared/error_messages', object: f.object

      - unless @chapter.cite_id.blank?
        = hidden_field_tag :cite_id, @chapter.cite_id
      = hidden_field_tag :novel_id, @novel.id

      - if @has_manage_novel_permission
        = f.label :number, t('activerecord.attributes.chapter.number')
        = f.text_field :number, class: 'form-control'

        = label :author_name, t('activerecord.attributes.chapter.author_id')
        = text_field_tag :author_name, '',class: 'form-control'

        = f.label :status, t('activerecord.attributes.chapter.status')
        = f.select :status, chapter_status_for_select_tag, class: 'form-control'

      = f.label :title, t('activerecord.attributes.chapter.title')
      = f.text_field :title, class: 'form-control'

      = f.label :summary, t('activerecord.attributes.chapter.summary')
      = f.text_area :summary, class: 'form-control'

      = f.label :content, t('activerecord.attributes.chapter.content')
      = f.text_area :content, rows:40, class: 'form-control'

      = f.label :subsequent_summary, t('activerecord.attributes.chapter.subsequent_summary')
      = f.text_area :subsequent_summary, class: 'form-control'

      = f.label :foreshadowing, t('activerecord.attributes.chapter.foreshadowing')
      = f.text_area :foreshadowing, class: 'form-control'

      = f.submit t('pages.add'), class: 'btn btn-primary'

app/views/chapters/show.html.haml
- provide :title, @chapter.full_title

.col-md-8.col-md-offset-2
  .row
    %h3.col-md-6= @chapter.full_title
    .col-md-6
      - if logged_in? and @chapter.status == Chapter::Status::ACTIVE
        = link_to '顶', chapter_votes_path(rate:1, chapter_id:@chapter.id), method: :post, class: 'btn btn-default'
        = link_to '踩', chapter_votes_path(rate:-1, chapter_id:@chapter.id), method: :post, class: 'btn btn-default'
      - if logged_in? and ( current_user.id == @chapter.author_id or current_user.has_permission?(Permission::MANAGE_NOVELS))
        = link_to '修改', edit_chapter_path(@chapter), class: 'btn btn-default'
      - if logged_in? and (@chapter.status == Chapter::Status::ACTIVE)
        = link_to '引用', new_chapter_path(cite_id:@chapter.id), class: 'btn btn-default'
      - if logged_in? and ( current_user.id == @chapter.author_id or current_user.has_permission?(Permission::MANAGE_NOVELS))
        = link_to '删除', chapter_path(@chapter), method: :delete, class: 'btn btn-default',  data: { confirm: t('pages.confirm') }
        = link_to '目录', @chapter.novel, class: 'btn btn-default'

  .chapter_content
    = to_html @chapter.content


  %h4
    评论区

  .chapter_comments
    - @chapter.chapter_comments.each do |chapter_comment|
      = render 'comments', chapter_comment: chapter_comment

  - if logged_in?
    %h4
      写评论
    .write_chapter_comments
      = form_for(:chapter_comment, url: chapter_comments_path) do |f|
        /= render 'shared/error_messages', object: f.object
        = hidden_field_tag :chapter_id, @chapter.id
        = f.text_area :content , class: 'form-control'
        = f.button '提交', class: 'btn btn-default'