config/routes.rb
Rails.application.routes.draw do



  root 'static_pages#home'

  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  resources :users
  resources :user_groups
  resources :novels
  resources :categories
  resources :chapters, only: [:create, :destroy, :show, :update, :edit, :new]
  resources :novel_comments, only: [:create, :destroy, :update]
  resources :chapter_comments, only: [:create, :destroy, :update]
  resources :chapter_votes, only: [:create, :destroy, :update]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    #{t('page_title.main')}  by OnePiece Studio with 陈大才, 刘京杭, 李顺喜.
  %nav
    %ul
      %li= link_to t('page_title.help'),   help_path
      %li= link_to t('page_title.about'),   about_path
      %li= link_to t('page_title.contact'), contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container
    = link_to t('page_title.main'), root_path, id: "logo"
    %nav
      %ul.nav.navbar-nav.navbar-right
        %li= link_to t('page_title.home'),   root_path
        - if logged_in?
          - if current_user.has_permission?(Permission::VIEW_USERS)
            %li= link_to t('pages.header.user_manage'), users_path

          - if current_user.has_permission?(Permission::MANAGE_NOVELS)
            %li= link_to t('pages.header.novel_manage'), novels_path

          %li= link_to t('pages.header.my_bookshelf'), '#'
          %li.dropdown
            %a.dropdown-toggle{href:'#', 'data-toggle' => 'dropdown'}
              = current_user.nick_name
              - key_name = "activerecord.attributes.user_group.#{current_user.user_group.name}"
              (#{ t(key_name) } #{ current_user.level } 级)
              %b.caret
            %ul.dropdown-menu
              %li= link_to t('pages.header.profile'), current_user
              %li= link_to t('pages.header.settings'), edit_user_path(current_user)
              %li.divider
              %li
                = link_to t('pages.logout'), logout_path, method: :delete
        - else
          %li= link_to t('pages.login'), login_path
          %li= link_to t('pages.signup'), signup_path

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 
                                              'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>